// Session actions
export const LOG_IN_SUCCESS = 'LOG_IN_SUCCESS';
export const LOG_IN_REQUEST = 'LOG_IN_REQUEST';
export const LOG_IN_ERROR = 'LOG_IN_ERROR';
export const LOG_OUT_SUCCESS = 'LOG_OUT_SUCCESS';

export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS';
export const SIGN_UP_REQUEST = 'SIGN_UP_REQUEST';
export const SIGN_UP_ERROR = 'SIGN_UP_ERROR';

// Signup to debate actions
export const SORTED_ROOMS_IS_FETCHING = 'SORTED_ROOMS_IS_FETCHING';
export const SORTED_ROOMS_ERROR = 'SORTED_ROOMS_ERROR';
export const FETCH_SORTED_ROOMS_SUCCESS = 'FETCH_SORTED_ROOMS_SUCCESS';

// Sorted Rooms actions
export const DEBATE_SIGN_UP_SUCCESS = 'DEBATE_SIGN_UP_SUCCESS';
export const DEBATE_SIGN_UP_REQUEST = 'DEBATE_SIGN_UP_REQUEST';
export const DEBATE_SIGN_UP_ERROR = 'DEBATE_SIGN_UP_ERROR';

// VPI Preferences actions
export const VPI_PREFERENCES_SUCCESS = 'VPI_PREFERENCES_SUCCESS';
export const VPI_PREFERENCES_ERROR = 'VPI_PREFERENCES_ERROR';
export const VPI_PREFERENCES_REQUEST = 'VPI_PREFERENCES_REQUEST';
